import { useState, useEffect } from 'react';
import { BUSINESS_VERTICALS } from '../data';
import { Asset, BusinessVertical } from '../types';
import { Sparkles, Calendar, Calculator, TrendingUp, Coins, Zap, HelpCircle } from 'lucide-react';

interface RoiSimulatorProps {
  onPreFillContact: (verticalName: string, assetName: string, estimatedUsage: number, message: string) => void;
}

export default function RoiSimulator({ onPreFillContact }: RoiSimulatorProps) {
  const [selectedVerticalId, setSelectedVerticalId] = useState<string>('ghost_kitchens');
  const [selectedAssetId, setSelectedAssetId] = useState<string>('combi_oven');
  
  // Find current structures
  const currentVertical = BUSINESS_VERTICALS.find(v => v.id === selectedVerticalId) || BUSINESS_VERTICALS[0];
  const currentAsset = currentVertical.assets.find(a => a.id === selectedAssetId) || currentVertical.assets[0];

  // Simulator Inputs (initialized from current asset values)
  const [monthlyUses, setMonthlyUses] = useState<number>(currentAsset.defaultUsesPerMonth);
  const [chargePerUse, setChargePerUse] = useState<number>(currentAsset.avgChargePerUse);
  const [useSplitModel, setUseSplitModel] = useState<boolean>(currentAsset.hasSplitModel);

  // Update slider bounds & defaults when asset changes
  useEffect(() => {
    setMonthlyUses(currentAsset.defaultUsesPerMonth);
    setChargePerUse(currentAsset.avgChargePerUse);
    setUseSplitModel(currentAsset.hasSplitModel);
  }, [selectedAssetId]);

  // Reset asset selection when vertical changes
  const handleVerticalChange = (verticalId: string) => {
    setSelectedVerticalId(verticalId);
    const firstAssetOfVertical = BUSINESS_VERTICALS.find(v => v.id === verticalId)?.assets[0];
    if (firstAssetOfVertical) {
      setSelectedAssetId(firstAssetOfVertical.id);
    }
  };

  // Calculations
  const assetCost = currentAsset.cost;
  const maintCost = currentAsset.monthlyMaint;
  
  // Total Gross Revenue generated by the machine per month
  const totalGrossRevenue = monthlyUses * chargePerUse;

  // CAPEX MODEL
  const capexNetMonth1 = totalGrossRevenue - assetCost - maintCost;
  const capexMonthlyNetAfterPayback = totalGrossRevenue - maintCost;
  const paybackMonths = capexMonthlyNetAfterPayback > 0 ? (assetCost / capexMonthlyNetAfterPayback) : 999;

  // OPEX MODEL (EQUIPY HAAS)
  let opexInitialCost = 0;
  let opexMonthlyCost = 0;
  let opexMonthlyNetProfit = 0;
  let opexLabel = '';

  if (useSplitModel) {
    opexLabel = 'Explotación Conjunta (Split 70/30)';
    opexMonthlyCost = 0; // Cost is 0
    opexMonthlyNetProfit = totalGrossRevenue * 0.30; // 30% clean commission for the space
  } else {
    opexLabel = `Renting Operativo Telemetría`;
    opexMonthlyCost = currentAsset.haasMonthlyRent || (assetCost * 0.04); // Fallback to 4%
    opexMonthlyNetProfit = Math.max(0, totalGrossRevenue - opexMonthlyCost);
  }

  const opexNetMonth1 = opexMonthlyNetProfit; // Profit starts from month 1 (0 initial cost)

  // Comparative Cashflow impact month 1
  const cashflowDifference = opexNetMonth1 - capexNetMonth1;

  const handleApplyHaaS = () => {
    const usageMessage = `Hola Equipy, estoy interesado en vuestra solución HaaS para el equipo "${currentAsset.name}" en un espacio de tipo "${currentVertical.name}". Mis parámetros simulados son: ${monthlyUses} ${currentAsset.metricUnit} al mes con un cargo estimado de ${chargePerUse.toFixed(2)}€ por uso, buscando un modelo de tipo ${useSplitModel ? 'Explotación Conjunta Split 70/30' : 'Renting Operativo por Telemetría'}. ¡Solicito propuesta personalizada!`;
    
    onPreFillContact(currentVertical.name, currentAsset.name, monthlyUses, usageMessage);
  };

  return (
    <section id="simulador" className="py-24 bg-brand-navy/5 relative overflow-hidden">
      {/* Decorative Orbs */}
      <div className="absolute top-1/2 left-0 w-96 h-96 rounded-full bg-brand-cyan/5 blur-[120px] pointer-events-none" />
      <div className="absolute bottom-0 right-0 w-96 h-96 rounded-full bg-brand-navy/5 blur-[120px] pointer-events-none" />

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        
        {/* Section Header */}
        <div className="text-center max-w-3xl mx-auto mb-16">
          <h2 className="text-xs uppercase font-extrabold tracking-widest text-brand-cyan bg-brand-navy/5 inline-block px-3.5 py-1.5 rounded-full mb-4">
            Calcular ROI
          </h2>
          <h3 className="font-display font-bold text-3xl sm:text-4xl text-brand-navy leading-tight">
            Descubre el Impacto Financiero Inmediato de EQUIPY HaaS
          </h3>
          <p className="text-gray-500 mt-4 text-sm sm:text-base">
            Compara el modelo de Compra Tradicional (CapEx) frente a nuestro modelo inteligente Hardware-as-a-Service (OpEx). Comprueba cómo liberas caja y maximizas ingresos desde el primer mes.
          </p>
          <div className="w-16 h-1 bg-brand-cyan mx-auto mt-4 rounded-full" />
        </div>

        {/* Simulator Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-stretch">
          
          {/* LEFT COLUMN: Inputs & Customizer (Col 5) */}
          <div className="lg:col-span-5 bg-white rounded-3xl p-6 sm:p-8 shadow-xl border border-brand-gray-mid flex flex-col justify-between">
            <div>
              <h4 className="font-display font-bold text-lg text-brand-navy mb-6 flex items-center space-x-2">
                <Calculator className="w-5 h-5 text-brand-cyan" />
                <span>Configura tus Parámetros</span>
              </h4>

              {/* 1. Select Business Vertical */}
              <div className="mb-6">
                <label className="block text-xs font-extrabold text-brand-navy uppercase tracking-wider mb-2.5">
                  1. Sector de Actividad
                </label>
                <div className="grid grid-cols-3 gap-2">
                  {BUSINESS_VERTICALS.map((vertical) => (
                    <button
                      key={vertical.id}
                      onClick={() => handleVerticalChange(vertical.id)}
                      className={`py-3 px-2 rounded-xl text-xs font-bold transition-all flex flex-col items-center justify-center space-y-1 text-center border ${
                        selectedVerticalId === vertical.id
                          ? 'border-brand-cyan bg-brand-navy text-white shadow-md'
                          : 'border-brand-gray-mid bg-brand-gray-light text-gray-500 hover:text-brand-navy hover:bg-brand-gray-mid/50'
                      }`}
                    >
                      <span className="block font-medium leading-none text-[10px] sm:text-[11px]">{vertical.name}</span>
                    </button>
                  ))}
                </div>
              </div>

              {/* 2. Select Asset */}
              <div className="mb-6">
                <label className="block text-xs font-extrabold text-brand-navy uppercase tracking-wider mb-2">
                  2. Equipo de Maquinaria Especializada
                </label>
                <select
                  value={selectedAssetId}
                  onChange={(e) => setSelectedAssetId(e.target.value)}
                  className="w-full bg-brand-gray-light border border-brand-gray-mid text-brand-navy rounded-xl px-4 py-3 text-sm font-semibold focus:outline-none focus:border-brand-cyan"
                >
                  {currentVertical.assets.map((asset) => (
                    <option key={asset.id} value={asset.id}>
                      {asset.name} (Valor: {asset.cost.toLocaleString('es-ES')}€)
                    </option>
                  ))}
                </select>
                <p className="text-[11px] text-gray-500 mt-2 italic">
                  {currentAsset.description}
                </p>
              </div>

              {/* 3. Toggle Split model if available */}
              {currentAsset.hasSplitModel && (
                <div className="mb-6 bg-brand-cyan/10 border border-brand-cyan/20 rounded-xl p-4 flex items-center justify-between">
                  <div>
                    <span className="text-xs font-extrabold text-brand-navy block uppercase tracking-wider">
                      Modelo Split 70/30 Disponible
                    </span>
                    <span className="text-[10px] text-gray-600 block mt-0.5">
                      Socio explotador. 30% del rendimiento limpio para ti sin cuotas.
                    </span>
                  </div>
                  <button
                    onClick={() => setUseSplitModel(!useSplitModel)}
                    className={`relative inline-flex h-6 w-11 items-center rounded-full transition-colors ${
                      useSplitModel ? 'bg-brand-navy' : 'bg-gray-300'
                    }`}
                  >
                    <span
                      className={`inline-block h-4 w-4 transform rounded-full bg-brand-cyan transition-transform ${
                        useSplitModel ? 'translate-x-6' : 'translate-x-1'
                      }`}
                    />
                  </button>
                </div>
              )}

              {/* 4. Estimated usage hours/sessions per month */}
              <div className="mb-6">
                <div className="flex justify-between items-center mb-1">
                  <label className="block text-xs font-extrabold text-brand-navy uppercase tracking-wider">
                    3. Uso Estimado Mensual
                  </label>
                  <span className="text-xs font-mono font-bold bg-brand-navy/5 text-brand-navy px-2 py-0.5 rounded">
                    {monthlyUses} {currentAsset.metricUnit}
                  </span>
                </div>
                <input
                  type="range"
                  min={Math.round(currentAsset.defaultUsesPerMonth * 0.2)}
                  max={Math.round(currentAsset.defaultUsesPerMonth * 2.5)}
                  value={monthlyUses}
                  onChange={(e) => setMonthlyUses(parseInt(e.target.value))}
                  className="w-full h-1.5 bg-brand-gray-mid rounded-lg appearance-none cursor-pointer accent-brand-cyan"
                />
                <div className="flex justify-between text-[9px] text-gray-400 mt-1 font-mono">
                  <span>Mínimo</span>
                  <span>Predeterminado: {currentAsset.defaultUsesPerMonth}</span>
                  <span>Máximo</span>
                </div>
              </div>

              {/* 5. Pricing charged to end user */}
              <div className="mb-6">
                <div className="flex justify-between items-center mb-1">
                  <label className="block text-xs font-extrabold text-brand-navy uppercase tracking-wider">
                    4. Precio Cobrado por Uso
                  </label>
                  <span className="text-xs font-mono font-bold bg-brand-navy/5 text-brand-navy px-2 py-0.5 rounded">
                    {chargePerUse.toFixed(2)} €
                  </span>
                </div>
                <input
                  type="range"
                  min={Math.round(currentAsset.avgChargePerUse * 0.4 * 10) / 10}
                  max={Math.round(currentAsset.avgChargePerUse * 2.0 * 10) / 10}
                  step="0.5"
                  value={chargePerUse}
                  onChange={(e) => setChargePerUse(parseFloat(e.target.value))}
                  className="w-full h-1.5 bg-brand-gray-mid rounded-lg appearance-none cursor-pointer accent-brand-cyan"
                />
                <div className="flex justify-between text-[9px] text-gray-400 mt-1 font-mono">
                  <span>Bajo</span>
                  <span>Sugerido: {currentAsset.avgChargePerUse}€</span>
                  <span>Premium</span>
                </div>
              </div>
            </div>

            <div className="bg-brand-gray-light border border-brand-gray-mid rounded-2xl p-4 mt-4 flex items-center space-x-3">
              <div className="bg-brand-cyan/10 p-2 rounded-xl text-brand-navy">
                <TrendingUp className="w-5 h-5" />
              </div>
              <p className="text-xs text-gray-600 leading-relaxed">
                Este simulador utiliza <strong>cifras estimadas</strong> para proyectar el rendimiento. Para más información y un análisis exacto de tus necesidades, <strong>contáctanos para realizar una propuesta totalmente a medida</strong> adaptada a tu espacio.
              </p>
            </div>
          </div>

          {/* RIGHT COLUMN: Comparative Dash (Col 7) */}
          <div className="lg:col-span-7 bg-brand-dark rounded-3xl p-6 sm:p-8 text-white border border-brand-navy/30 flex flex-col justify-between shadow-xl relative overflow-hidden">
            <div className="absolute inset-0 bg-gradient-to-tr from-brand-navy/10 to-transparent pointer-events-none" />
            
            <div className="relative z-10">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 mb-6 pb-6 border-b border-white/10">
                <h4 className="font-display font-bold text-lg text-white flex items-center space-x-2">
                  <Sparkles className="text-brand-cyan w-5 h-5 animate-pulse" />
                  <span>Análisis Comparativo Financiero</span>
                </h4>
                <span className="text-xs text-brand-cyan font-semibold font-mono bg-brand-navy/60 border border-brand-cyan/20 px-3 py-1 rounded-full uppercase tracking-wider">
                  {opexLabel}
                </span>
              </div>

              {/* Comparative Matrix Grid */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
                
                {/* CapEx Traditional Card */}
                <div className="bg-white/5 border border-white/5 rounded-2xl p-5 space-y-4">
                  <div className="flex justify-between items-center">
                    <span className="text-xs uppercase tracking-wider font-extrabold text-gray-400">Compra Tradicional</span>
                    <span className="text-[9px] bg-red-950 border border-red-500/20 text-red-400 px-1.5 py-0.5 rounded font-bold">CapEx</span>
                  </div>

                  <div>
                    <span className="text-gray-400 text-xs block">Inversión Inicial Desembolsada:</span>
                    <span className="text-xl sm:text-2xl font-display font-extrabold text-red-400">
                      -{assetCost.toLocaleString('es-ES')} €
                    </span>
                  </div>

                  <div className="space-y-1 text-xs">
                    <div className="flex justify-between">
                      <span className="text-gray-400">Mantenimiento mensual:</span>
                      <span className="font-mono text-gray-200">{maintCost} €</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-gray-400">Retorno de inversión (ROI):</span>
                      <span className="font-mono text-gray-200">
                        {paybackMonths === 999 ? 'Inviable' : `${paybackMonths.toFixed(1)} meses`}
                      </span>
                    </div>
                    <div className="flex justify-between pt-2 border-t border-white/5">
                      <span className="text-gray-400 font-bold">Neto Mes 1 (con compra):</span>
                      <span className="font-mono font-bold text-red-300">
                        {capexNetMonth1.toLocaleString('es-ES')} €
                      </span>
                    </div>
                  </div>
                </div>

                {/* OpEx Equipy HaaS Card */}
                <div className="bg-brand-navy/40 border border-brand-cyan/30 rounded-2xl p-5 space-y-4 shadow-[0_4px_25px_rgba(0,191,255,0.08)]">
                  <div className="flex justify-between items-center">
                    <span className="text-xs uppercase tracking-wider font-extrabold text-brand-cyan">Modelo HaaS EQUIPY</span>
                    <span className="text-[9px] bg-brand-cyan text-brand-deep px-1.5 py-0.5 rounded font-extrabold">OpEx</span>
                  </div>

                  <div>
                    <span className="text-gray-300 text-xs block">Inversión Inicial Desembolsada:</span>
                    <span className="text-xl sm:text-2xl font-display font-extrabold text-brand-cyan flex items-center">
                      0 € <span className="text-xs font-normal text-gray-400 ml-1.5">(Cero Inversión)</span>
                    </span>
                  </div>

                  <div className="space-y-1 text-xs">
                    <div className="flex justify-between">
                      <span className="text-gray-300">Coste de equipamiento / Split:</span>
                      <span className="font-mono text-brand-cyan font-bold">
                        {useSplitModel ? '0 €' : `${opexMonthlyCost} € / mes`}
                      </span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-gray-300">Soporte y Reparaciones SAT:</span>
                      <span className="font-mono text-green-400 font-semibold">Gratis (Incluido)</span>
                    </div>
                    <div className="flex justify-between pt-2 border-t border-white/10">
                      <span className="text-brand-cyan font-bold">Neto Mes 1 (Facturado):</span>
                      <span className="font-mono font-bold text-green-400">
                        +{opexNetMonth1.toLocaleString('es-ES')} €
                      </span>
                    </div>
                  </div>
                </div>

              </div>

              {/* Comparative Cashflow Highlight Bar */}
              <div className="bg-white/5 border border-white/10 rounded-2xl p-5 mb-8">
                <span className="text-xs uppercase tracking-widest text-gray-400 block mb-2">
                  Diferencia de Caja Libre en el Mes 1
                </span>
                <div className="flex items-center space-x-4">
                  <div className="bg-brand-cyan/10 p-2.5 rounded-xl text-brand-cyan">
                    <Coins className="w-6 h-6" />
                  </div>
                  <div>
                    <span className="text-xs text-gray-400 block">Efectivo preservado en caja en tu primer mes:</span>
                    <div className="flex items-baseline space-x-2">
                      <span className="text-2xl font-display font-extrabold text-green-400">
                        +{cashflowDifference.toLocaleString('es-ES')} €
                      </span>
                      <span className="text-xs text-brand-cyan font-semibold">liberados con EQUIPY HaaS</span>
                    </div>
                  </div>
                </div>

                {/* Graph Simulator Visual bar */}
                <div className="mt-4 space-y-2">
                  <div className="flex justify-between text-[10px] text-gray-400 font-mono">
                    <span>Mes 1 Flujo de Caja</span>
                    <span>{capexNetMonth1 < 0 ? 'CapEx Negativo (-)' : 'Neutral'} vs HaaS Positivo (+)</span>
                  </div>
                  <div className="relative h-6 w-full bg-black/40 rounded-full overflow-hidden flex">
                    <div 
                      className="bg-red-500 h-full transition-all duration-500"
                      style={{ width: `${Math.min(50, Math.max(5, (assetCost / (assetCost + totalGrossRevenue)) * 50))}%` }}
                    />
                    <div className="bg-neutral-800 h-full w-[2px]" />
                    <div 
                      className="bg-brand-cyan h-full transition-all duration-500 flex items-center justify-end pr-3"
                      style={{ width: `${Math.min(95, Math.max(50, 100 - (assetCost / (assetCost + totalGrossRevenue)) * 50))}%` }}
                    >
                      <span className="text-[9px] font-bold text-brand-deep font-mono">RENTABILIDAD DESDE EL DÍA 1</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            {/* Action Section inside simulator Card */}
            <div className="relative z-10 pt-4 border-t border-white/10 flex flex-col sm:flex-row items-center justify-between gap-4">
              <div className="text-center sm:text-left">
                <span className="text-[11px] text-gray-400 block">Facturación Total Generada por el Activo:</span>
                <span className="text-lg font-mono font-bold text-gray-200">
                  {totalGrossRevenue.toLocaleString('es-ES')} € / mes
                </span>
              </div>
              <button
                onClick={handleApplyHaaS}
                className="w-full sm:w-auto bg-brand-cyan hover:bg-cyan-400 text-brand-deep font-bold px-6 py-3.5 rounded-xl flex items-center justify-center space-x-2 transition-all hover:scale-103 shadow-lg"
              >
                <Zap className="w-4 h-4 fill-brand-deep" />
                <span>Solicitar HaaS para este Equipo</span>
              </button>
            </div>

          </div>

        </div>

      </div>
    </section>
  );
}
